version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    asdf:
      uv: latest
  commands:
    - uv sync --frozen --group docs
    - uv run mkdocs build -d $READTHEDOCS_OUTPUT/html

mkdocs:
  fail_on_warning: false
